//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondensadoPaciente
    {
        public int idCondensado { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Folio { get; set; }
        public string CURP { get; set; }
        public Nullable<int> idCita { get; set; }
        public string TipoPago { get; set; }
        public Nullable<System.DateTime> FechaReferencia { get; set; }
        public string NoOrden { get; set; }
        public string EstatusPago { get; set; }
        public string TipoLicencia { get; set; }
        public string NoExpediente { get; set; }
        public Nullable<System.DateTime> FechaCita { get; set; }
        public string Sucursal { get; set; }
        public string Doctor { get; set; }
        public string Recepcionista { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public string TipoTramite { get; set; }
        public string Referencia { get; set; }
        public string Canal { get; set; }
        public string CC { get; set; }
        public string Asistencia { get; set; }
        public string CancelaComentario { get; set; }
        public string Entregado { get; set; }
        public string ReferidoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Cuenta { get; set; }
        public string CanalTipo { get; set; }
        public string CuentaComentario { get; set; }
        public string Conciliado { get; set; }
        public Nullable<System.DateTime> FechaContable { get; set; }
        public string UsarSaldo { get; set; }
        public string FormaPago { get; set; }
        public string PrecioEpi { get; set; }
        public string ConciliarPago { get; set; }
        public string RastreoPagos { get; set; }
        public string Venta { get; set; }
        public string IVA { get; set; }
        public string CostoSeguro { get; set; }
        public string IvaSeguro { get; set; }
        public string TotalSeguro { get; set; }
        public string TotalVenta { get; set; }
        public string ventaSeguro { get; set; }
        public string TotalIVA { get; set; }
        public string TotalVentaIVA { get; set; }
        public Nullable<int> idCaptura { get; set; }
        public string EstatusCaptura { get; set; }
        public Nullable<System.DateTime> InicioCaptura { get; set; }
        public Nullable<System.DateTime> FinalCaptura { get; set; }
        public Nullable<System.DateTime> FechaExpdiente { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Aptitud { get; set; }
        public string ComentarioAptitud { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
    }
}
